# docker-compose.yml

version: '3.8'

services:
  app:
    build:
      context: ./app
    networks:
      - app_net
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/mydatabase

  db:
    image: postgres:13
    networks:
      - db_net
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  nginx:
    image: nginx:1.27.0-bookworm-perl
    volumes:
      - ./Nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_net
    ports:
      - "8080:80"

networks:
  app_net:
  db_net: